spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  sql:
    init:
      mode: always
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome